import { FailoverStatus } from '../truenas/webui/enums/failover-status.enum';
import { Alert } from '../truenas/webui/interfaces/alert.interface';
import { ChartRelease, ChartReleaseStats } from '../truenas/webui/interfaces/chart-release.interface';
import { PullContainerImageResponse, PullContainerImageParams, ContainerImage } from '../truenas/webui/interfaces/container-image.interface';
import { DirectoryServicesState } from '../truenas/webui/interfaces/directory-services-state.interface';
import { FailoverDisabledReasonEvent } from '../truenas/webui/interfaces/failover-disabled-reasons.interface';
import { Group } from '../truenas/webui/interfaces/group.interface';
import { Job } from '../truenas/webui/interfaces/job.interface';
import { KubernetesStatusData } from '../truenas/webui/interfaces/kubernetes-status-data.interface';
import { Pool } from '../truenas/webui/interfaces/pool.interface';
import { ReportingRealtimeUpdate } from '../truenas/webui/interfaces/reporting.interface';
import { PoolScan } from '../truenas/webui/interfaces/resilver-job.interface';
import { Service } from '../truenas/webui/interfaces/service.interface';
import { SmartTestProgressUpdate } from '../truenas/webui/interfaces/smart-test-progress.interface';
import { Disk } from '../truenas/webui/interfaces/storage.interface';
import { TrueCommandConfig } from '../truenas/webui/interfaces/true-command-config.interface';
import { User } from '../truenas/webui/interfaces/user.interface';
import { VirtualMachine } from '../truenas/webui/interfaces/virtual-machine.interface';
import { ZfsSnapshot } from '../truenas/webui/interfaces/zfs-snapshot.interface';
import { SystemHealth } from '../system-health.interface';

export interface ApiEventDirectory {
    'alert.list': { response: Alert };
    'chart.release.query': { response: ChartRelease };
    'chart.release.statistics': { response: { id: string; stats: ChartReleaseStats } };
    'core.get_jobs': { response: Job };
    'directoryservices.status': { response: DirectoryServicesState };
    'failover.status': { response: { status: FailoverStatus } };
    'failover.disabled.reasons': { response: FailoverDisabledReasonEvent };
    'service.query': { response: Service };
    'truecommand.config': { response: TrueCommandConfig };
    'vm.query': { response: VirtualMachine };
    'zfs.snapshot.query': { response: ZfsSnapshot };
    'zfs.pool.scan': { response: PoolScan };
    'user.query': { response: User };
    'container.image.pull': { response: Job<PullContainerImageResponse, PullContainerImageParams> };
    'disk.query': { response: Disk };
    'pool.query': { response: Pool };
    'group.query': { response: Group };
    'container.image.query': { response: ContainerImage };
    'reporting.realtime': { response: ReportingRealtimeUpdate };
    'smart.test.progress': { response: SmartTestProgressUpdate };
    'kubernetes.state': { response: KubernetesStatusData };
    'system.health': { response: SystemHealth };
}
