// Generated by ts-to-zod
import { z } from "zod";
import {
  AppJobAction,
  AppSpec,
  AppPermission,
  AppsError,
  AppsWarning,
  AppsActions,
  InstallationQuestionType,
} from "./apps";

import { fileAccessSchema } from "./server-schema";

export const appJobActionSchema = z.nativeEnum(AppJobAction);

export const appBasicsSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  version: z.string(),
  icon: z.string(),
  train: z.string(),
});

export const appSpecSchema = z.nativeEnum(AppSpec);

export const appPermissionSchema = z.nativeEnum(AppPermission);

export const appMaintainerSchema = z.object({
  name: z.string(),
  email: z.string(),
});

export const appsErrorSchema = z.nativeEnum(AppsError);

export const appsWarningSchema = z.nativeEnum(AppsWarning);

export const appsActionsSchema = z.nativeEnum(AppsActions);

export const appsHealthSchema = z.object({
  healthy: z.boolean(),
  errors: z.array(appsErrorSchema),
  warnings: z.array(appsWarningSchema),
  actions_available: z.array(appsActionsSchema),
});

export const installationQuestionTypeSchema = z.nativeEnum(
  InstallationQuestionType,
);

export const installationQuestionOptionSchema = z.object({
  text: z.string(),
  value: z.union([z.string(), z.number(), z.boolean()]),
});

export const installationQuestionSchema = z.object({
  question: z.string(),
  type: installationQuestionTypeSchema,
  key: z.string(),
  options: z.array(installationQuestionOptionSchema).optional(),
  required: z.boolean().optional(),
  default: z.union([z.string(), z.number(), z.boolean()]).optional(),
  placeholder: z.string().optional(),
  description: z.string().optional(),
});

const locationPreferenceIdSchema = z.any();

const appStateSchema = z.any();

const chartFormValueSchema = z.any();

export const appRequirementsSchema = z.object({
  permissions: z.array(appPermissionSchema),
  specifications: z.array(appSpecSchema),
  locations: z.array(locationPreferenceIdSchema),
  ports: z.array(z.number()),
});

export const appRequirementsCheckSchema = z.object({
  permissions: z.object({
    met: z.array(appPermissionSchema),
    unmet: z.array(appPermissionSchema),
  }),
  specifications: z.object({
    met: z.array(appSpecSchema),
    unmet: z.array(appSpecSchema),
  }),
  locations: z.object({
    met: z.array(locationPreferenceIdSchema),
    unmet: z.array(locationPreferenceIdSchema),
  }),
});

export const appListingSchema = z.object({
  appId: z.string(),
  name: z.string(),
  train: z.union([z.literal("stable"), z.literal("community")]),
  version: z.string(),
  appVersion: z.string(),
  description: z.string(),
  icon: z.string(),
  categories: z.array(z.string()),
  keywords: z.array(z.string()),
  maintainers: z.array(appMaintainerSchema),
  screenshots: z.array(z.string()),
  sources: z.array(z.string()),
  homepage: z.string(),
  recommended: z.boolean(),
  supported: z.boolean(),
  fresh: z.boolean(),
  installScript: z.string().optional(),
  requirements: appRequirementsSchema.optional(),
});

export const appInfoSchema = appBasicsSchema.extend({
  status: appStateSchema,
  url_webui: z.string(),
  upgradeAvailable: z.boolean(),
  updatedScriptAvailable: z.boolean(),
  latestVersion: z.string(),
});

export const appInfoDetailedSchema = appInfoSchema.extend({
  data: z.array(z.array(z.number())),
});

const appsInstallScriptV1Schema = z.object({
  version: z.literal(1),
  requirements: appRequirementsSchema.optional(),
  ensure_directories_exists: z
    .array(
      z.union([
        z.string(),
        z.object({
          path: z.string(),
          network_share: z.boolean().optional(),
          posix: z.boolean().optional(),
        }),
      ]),
    )
    .optional(),
  ensure_permissions_exists: z
    .array(
      z.object({
        path: z.string(),
        username: z.string(),
        access: fileAccessSchema,
        posix: z
          .object({
            groupname: z.string(),
          })
          .optional(),
      }),
    )
    .optional(),
  app_values: z.record(chartFormValueSchema),
});

const appsInstallScriptV2Schema = z.object({
  version: z.literal(2),
  requirements: appRequirementsSchema.optional(),
  installation_questions: z.array(installationQuestionSchema).optional(),
  ensure_directories_exists: z
    .array(
      z.union([
        z.string(),
        z.object({
          path: z.string(),
          network_share: z.boolean().optional(),
          posix: z.boolean().optional(),
        }),
      ]),
    )
    .optional(),
  ensure_permissions_exists: z
    .array(
      z.object({
        path: z.string(),
        username: z.string(),
        access: fileAccessSchema,
        posix: z
          .object({
            groupname: z.string(),
          })
          .optional(),
      }),
    )
    .optional(),
  app_values: z.record(chartFormValueSchema),
});

const appsInstallScriptV3Schema = appsInstallScriptV2Schema
  .omit({ version: true, requirements: true })
  .extend({
    version: z.literal(3),
    script: z.object({
      version: z.string(),
      updateCompatibility: z.string().optional(),
      changeLog: z.string().optional(),
    }),
    requirements: appRequirementsSchema,
  });

export const appsInstallScriptSchema = z.union([
  appsInstallScriptV1Schema,
  appsInstallScriptV2Schema,
  appsInstallScriptV3Schema,
]);

export const appConfigurationSchema = z.object({
  installScript: appsInstallScriptSchema.optional().nullable(),
  questionResponses: z
    .record(z.union([z.string(), z.number(), z.boolean()]))
    .optional(),
});

export const installScriptCurationSchema = z.object({
  name: z.string(),
  url: z.string(),
  script: appsInstallScriptSchema,
});
