export enum GlobalErrorCode {
    AUTH_INVALID_2FA = 'AUTH_INVALID_2FA',
    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    AUTH_MISSING_2FA = 'AUTH_MISSING_2FA',
    AUTH_MISSING_CREDENTIALS = 'AUTH_MISSING_CREDENTIALS',
    AUTH_NOT_ADMIN = 'AUTH_NOT_ADMIN',
    GENERIC_SERVER_ERROR = 'GENERIC_SERVER_ERROR',
    GENERIC_USER_ERROR = 'GENERIC_USER_ERROR',
    GENERIC_WEBSOCKET_ERROR = 'GENERIC_WEBSOCKET_ERROR',
    SERVER_NOT_CONNECTED = 'Server not currently connected',
    INSTALL_APP_NO_APP_ID = 'App id not provided in request',
    INSTALL_APP_NOT_SUPPORTED_AND_NO_SCRIPT = 'Supported app not found and no install script provided',
    INSTALL_APP_NO_TRAIN_PROVIDED = 'Train is required if install script is provided',
    INSTALL_APP_DOCKER_HUB_RATE_LIMIT = 'Docker Hub rate limit exceeded, wait a few hours for it to reset',
    PROCESS_INSTALL_SCRIPT_FAILED_JSON_PARSE = 'Failed to JSON parse install script',
    PROCESS_INSTALL_SCRIPT_INVALID_JSON = 'Install script must be a valid JSON object',
    PROCESS_INSTALL_SCRIPT_MISSING_VERSION = 'Install script must have a "version" field',
    PROCESS_INSTALL_SCRIPT_UNSUPPORTED_VERSION = 'Unsupported install script version',
    PROCESS_INSTALL_SCRIPT_MISSING_APP_VALUES = 'Install script must have an "app_values" field',
    PROCESS_INSTALL_SCRIPT_UNKNOWN_LOCATION = 'Install script has an unknown location',
    PROCESS_INSTALL_SCRIPT_INVALID_RANDOM_STRING_LENGTH = 'Install script has an invalid random string length',
    PROCESS_INSTALL_SCRIPT_FAILED_JSON_PARSE_AFTER = 'Failed to JSON parse install script after processing',
    PROCESS_INSTALL_SCRIPT_INVALID_MEMORY_PERCENTAGE = 'Install script has an invalid memory percentage',
    PROCESS_INSTALL_SCRIPT_INVALID_MEMORY_VALUE = 'Install script has an invalid memory value',
    RUN_INSTALL_SCRIPT_UNSUPPORTED_VERSION = 'Install script must have a "version" field',
    DDP_CLIENT_DISCONNECTED = 'DDPClient disconnected from DDP server',
}
