export enum GlobalErrorCode {
    AUTH_MISSING_2FA = 'AUTH_MISSING_2FA',
    AUTH_MISSING_CREDENTIALS = 'AUTH_MISSING_CREDENTIALS',
    AUTH_NOT_ADMIN = 'AUTH_NOT_ADMIN',
    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    GENERIC_SERVER_ERROR = 'GENERIC_SERVER_ERROR',
}