// Generated by ts-to-zod
import { z } from "zod";
import {
  UserGroups,
  UserPreferenceTheme,
  UserPreferenceTemperature,
  UserPurchaseType,
} from "./user";

export const userGroupsSchema = z.nativeEnum(UserGroups);

export const userPreferenceThemeSchema = z.nativeEnum(UserPreferenceTheme);

export const userPreferenceTemperatureSchema = z.nativeEnum(
  UserPreferenceTemperature,
);

export const userPurchaseTypeSchema = z.nativeEnum(UserPurchaseType);

export const newUserRequestSchema = z.object({
  name: z.string(),
  email: z.string(),
  password: z.string(),
  clientip: z.string().optional(),
});

const idSchema = z.any();

export const userPreferencesSchema = z.object({
  theme: userPreferenceThemeSchema,
  temperature: userPreferenceTemperatureSchema,
});

export const userPurchaseSchema = z.object({
  active: z.boolean(),
  purchase_type: userPurchaseTypeSchema,
  purchased: z.date().optional(),
  expiraration: z.date().optional(),
});

export const userSchema = z.object({
  id: idSchema,
  email: z.string(),
  name: z.string(),
  groups: z.array(userGroupsSchema).optional(),
  image: z.string().optional(),
  preferences: userPreferencesSchema.optional(),
  purchases: z.array(userPurchaseSchema).optional(),
});
